### ISSUE TITLE
Wave position

### ISSUE THREAD

**Issue by mclusky** [Svetloslav15/wave-generator#1]
Hi,

Great tool! thanks for sharing it. I need to create a div with a wavy top, but your tool seems to only generate waves at the bottom. Is there a way to change the wave position ? Basically I'd like the clip path to match the red shape.

**Comment by Svetloslav15** [comment]
Thanks for using the tool, you can generate the wave and then rotate it with 180 degrees and you will have wave at the top. 
<br> CSS: `transform: rotate(180deg)`

**Comment by mclusky** [comment]
thanks for getting back to me. the problem with doing that is I have content inside the wave (image and text), therefore everything inside the wave will also be rotated

**Comment by Svetloslav15** [comment]
You can create the wave div outside the div that is containing image and text. Give it some width and height and if necessary position it properly. I think this will resolve the problem 😃

**Comment by mclusky** [comment]
yeah, i thought i'd have to do something like that. ok, thanks for your help !
